IF EXISTS(SELECT 1 FROM sys.tables WHERE object_id = OBJECT_ID('Users'))
BEGIN;
    DROP TABLE [Users];
END;
GO

CREATE TABLE [Users] (
    [Id] INTEGER NOT NULL IDENTITY(1, 1),
    [FirstName] VARCHAR(255) NULL,
    [LastName] VARCHAR(255) NULL,
    [Email] VARCHAR(255) NULL,
    [Subscribed] bit NULL Default(1)
    PRIMARY KEY ([Id])
);
GO

INSERT INTO Users([FirstName],[LastName],[Email]) VALUES('Juliet','Park','sit.amet.metus@et.com'),('Ashton','Hart','dictum.eu.eleifend@dictumplacerat.co.uk'),('Leigh','Gonzales','ipsum@vulputate.com'),('Jamal','Emerson','Curae@convallisincursus.ca'),('Morgan','Mack','nisl.arcu.iaculis@odio.edu'),('Omar','Burch','ultrices@Aliquamgravida.ca'),('Dennis','Holland','ipsum.primis@tincidunt.org'),('Ray','Jacobson','nonummy@sapienimperdietornare.org'),('Paul','Trujillo','purus.ac.tellus@risusDonec.org'),('Lars','Norman','ornare.placerat@magnaa.org');
INSERT INTO Users([FirstName],[LastName],[Email]) VALUES('Robert','Cole','orci.Donec.nibh@Innecorci.net'),('Germane','Dillon','dictum.eleifend@luctus.com'),('Aretha','Mckee','metus.In.lorem@milaciniamattis.com'),('Arthur','Mccarthy','vulputate@etultrices.net'),('Burton','Hurley','accumsan.interdum.libero@Morbivehicula.org'),('Rashad','Barnes','orci.in.consequat@lorem.com'),('Neville','Wilder','sociosqu@loremluctusut.com'),('Keegan','Huffman','ridiculus.mus@imperdietnec.org'),('Heather','Conner','lacus@arcu.edu'),('Uriah','Booth','lacus.vestibulum.lorem@tellusloremeu.co.uk');
INSERT INTO Users([FirstName],[LastName],[Email]) VALUES('Dana','Bradshaw','cursus.vestibulum.Mauris@vestibulum.com'),('Portia','Johnson','Duis@Aliquamgravida.com'),('Eleanor','Hudson','sit.amet@consequatnec.co.uk'),('Tamekah','Stone','nascetur.ridiculus@fringilla.edu'),('Erasmus','Hoover','pretium.neque.Morbi@imperdietullamcorperDuis.net'),('Eleanor','Meadows','metus.facilisis.lorem@Vivamusmolestiedapibus.com'),('Jasper','Cash','Sed.nunc@vel.edu'),('Barclay','Lindsay','nec.ligula.consectetuer@DonecegestasAliquam.co.uk'),('Zachery','Lambert','Donec@varius.co.uk'),('Grant','Nguyen','arcu.Vestibulum.ante@ut.ca');
INSERT INTO Users([FirstName],[LastName],[Email]) VALUES('Abigail','Rivera','Mauris.blandit@dui.com'),('Jerry','Massey','nec.malesuada.ut@habitantmorbitristique.co.uk'),('Jemima','Hoffman','Fusce.mi.lorem@pretiumnequeMorbi.net'),('Maxwell','Farrell','faucibus@Classaptent.co.uk'),('Chandler','Glenn','et.magnis@dolornonummyac.ca'),('Macey','Kelly','augue.Sed.molestie@malesuadafames.ca'),('Dalton','Moses','egestas.Sed.pharetra@facilisisfacilisismagna.net'),('Lars','Witt','Vivamus@pharetraNamac.edu'),('Graiden','Wright','arcu.Vestibulum@antedictum.edu'),('Marcia','Whitfield','ultrices.sit@fringillapurus.co.uk');
INSERT INTO Users([FirstName],[LastName],[Email]) VALUES('Eden','Strong','vel@elementumpurusaccumsan.net'),('Galvin','Allison','eleifend.egestas.Sed@atiaculis.ca'),('Merrill','Conrad','non@mauris.org'),('Minerva','Kramer','Sed.auctor@necante.ca'),('Audra','Vinson','luctus@accumsaninterdumlibero.edu'),('Thor','Harvey','Suspendisse.sed@Vestibulumante.ca'),('Patrick','Franco','nec.tellus.Nunc@eleifendvitae.net'),('Xerxes','Bryan','nec.diam.Duis@elitpellentesque.net'),('Gail','Johns','non.arcu.Vivamus@maurissapien.co.uk'),('Kylynn','Nixon','Ut@dolorQuisquetincidunt.org');
INSERT INTO Users([FirstName],[LastName],[Email]) VALUES('Hakeem','Henry','cursus.luctus.ipsum@iaculisenimsit.co.uk'),('Marvin','Thomas','eleifend.nunc@volutpat.co.uk'),('Holly','Wright','a.arcu@Uttinciduntorci.net'),('Nolan','Saunders','semper.pretium.neque@sodales.ca'),('Jeanette','Hamilton','Cras@amagnaLorem.com'),('Bethany','Riley','mi.felis.adipiscing@vitaedolorDonec.edu'),('Grace','Gross','Cras.dictum.ultricies@diam.net'),('Indigo','Garza','lacinia.vitae.sodales@lectusjusto.co.uk'),('Stuart','Aguirre','mi.lacinia@magnased.edu'),('Walter','Moran','parturient.montes@metusInlorem.org');
INSERT INTO Users([FirstName],[LastName],[Email]) VALUES('Jordan','Reyes','Morbi.non@arcuet.edu'),('Cairo','Acevedo','est@arcu.ca'),('Kelsey','Taylor','amet.lorem@dolor.co.uk'),('Kasimir','Warren','Cras.pellentesque.Sed@lobortis.edu'),('Virginia','Albert','Mauris@lectusCumsociis.edu'),('Alvin','Shannon','elit.elit.fermentum@ut.co.uk'),('Bradley','Huff','faucibus@Curabitursed.edu'),('Griffin','Vaughan','tellus.justo@egestasascelerisque.co.uk'),('Barclay','Peterson','pharetra.Quisque.ac@dictummagna.co.uk'),('Piper','Molina','justo.faucibus.lectus@arcuVivamussit.org');
INSERT INTO Users([FirstName],[LastName],[Email]) VALUES('Montana','Greene','Etiam@Etiamvestibulummassa.org'),('Brielle','Velazquez','Praesent.eu.nulla@vitae.co.uk'),('Aubrey','Acosta','rutrum.Fusce@etmagnaPraesent.net'),('Richard','Spence','ridiculus.mus@mattisInteger.ca'),('Macon','Kirk','dignissim@accumsansed.net'),('Priscilla','Castro','Etiam@mi.co.uk'),('Sean','Hall','sem.magna.nec@orcitinciduntadipiscing.net'),('Indigo','Johnston','justo.sit.amet@Namtempor.com'),('Drake','Carr','magnis.dis@tempusrisusDonec.edu'),('Oprah','Cruz','ullamcorper.eu@tellusfaucibus.org');
INSERT INTO Users([FirstName],[LastName],[Email]) VALUES('Martha','Pittman','tempus.scelerisque@nibhdolor.org'),('Zena','Camacho','nonummy.ac@felisorciadipiscing.org'),('Brent','Boyle','justo@quis.com'),('Oscar','Bond','dictum.placerat@ac.com'),('Frances','Dunn','vulputate.nisi.sem@lobortisauguescelerisque.net'),('Ciara','Randall','lorem@sitametrisus.co.uk'),('Christopher','Navarro','sed.libero@aliquamadipiscinglacus.org'),('Camden','Richardson','turpis@ametluctusvulputate.ca'),('Ila','Winters','quam.dignissim.pharetra@metusVivamus.net'),('Donovan','Donovan','erat.Sed.nunc@ridiculusmus.co.uk');
INSERT INTO Users([FirstName],[LastName],[Email]) VALUES('Prescott','Mcdaniel','mattis.semper@id.com'),('Colt','Donaldson','mollis.Integer@nisisem.com'),('Blythe','Morales','ornare@Quisqueac.co.uk'),('Maia','Noel','malesuada.fames@scelerisquemollis.org'),('Yvette','Watts','vulputate.dui@arcueu.com'),('Lana','Mathis','augue@lobortis.ca'),('Rooney','King','eu.odio.tristique@Quisque.co.uk'),('Francis','Hess','Cras.convallis.convallis@eusem.net'),('Ignacia','Jimenez','fames.ac@nunc.net'),('Rhea','Gilliam','libero@montesnascetur.co.uk');
