version: "3.2"
services:
  db:
    image: mcr.microsoft.com/mssql/server:latest
    volumes:
        - ./container_db:/var/opt/mssql/data
    environment:
        ACCEPT_EULA: Y
        SA_PASSWORD: P@ssword123
    ports:
        - 6000:1433
  api:
    image:
        mcr.microsoft.com/dotnet/sdk:6.0
    volumes:
        - ./MinApi:/workspace
    working_dir: /workspace
    command: sh -c 'while true; do sleep 30; done'
    ports:
        - 7001:7000
    depends_on:
      - db
