CREATE TABLE dbo.Files(
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FileId] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
	[File] [varbinary](max) FILESTREAM  NULL,
 CONSTRAINT [PK_Vorlage] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
) WITH 
(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, 
ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) 
ON [PRIMARY] FILESTREAM_ON [DemoFS],
UNIQUE NONCLUSTERED 
(
	[FileId] ASC
) WITH 
(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, 
ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) 
ON [PRIMARY]
) ON [PRIMARY] FILESTREAM_ON [DemoFS]
GO